#Write a program to demonstrate how LU decomposition help in solving linear systems?

In [ ]:
import numpy as np
import scipy.linalg
A=np.array([[2,-1,0,0],
             [-1,2,-1,0],
             [0,-1,2,-1],
             [0,0,-1,2]])
b=np.array([3,-2,-2,3])
P,L,U=scipy.linalg.lu(A)
print("Lower Triangular matrix",L)
print("Upper Triangular matrix",U)
print("Permutation matrix",P)
x1=np.linalg.solve(A,b)
print("solution",x1)
error=np.dot(A,x1)-b
print("Error",error)

Lower Triangular matrix [[ 1.          0.          0.          0.        ]
 [-0.5         1.          0.          0.        ]
 [ 0.         -0.66666667  1.          0.        ]
 [ 0.          0.         -0.75        1.        ]]
Upper Triangular matrix [[ 2.         -1.          0.          0.        ]
 [ 0.          1.5        -1.          0.        ]
 [ 0.          0.          1.33333333 -1.        ]
 [ 0.          0.          0.          1.25      ]]
Permutation matrix [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
solution [ 1. -1. -1.  1.]
Error [0.0000000e+00 0.0000000e+00 0.0000000e+00 4.4408921e-16]


#How do different solution methods compare in computational efficiency?

In [ ]:
import numpy as np
import sympy as sp
import time
Num=50
A=np.random.rand(Num,Num)+Num*np.eye(Num)
b=np.random.rand(Num,1)
start_time=time.time()
x1=np.linalg.solve(A,b)
end_time=time.time()
print("LU",x1)
print("Time taken for LU",end_time-start_time)
start_time=time.time()
x2=np.linalg.inv(A)@b
end_time=time.time()
print("Inverses",x2)
print("Time taken for Inverse",end_time-start_time)
start_time=time.time()
C=np.hstack((A,b))
C=sp.Matrix(C)
D,_=C.rref()
R=np.array(D).astype(np.float64)
x3=R[:-1]
end_time=time.time()
print("RRef",x3)
print("Time taken for RREf",end_time-start_time)


LU [[ 4.81895882e-03]
 [ 7.66389541e-03]
 [ 1.57680255e-02]
 [ 1.17192567e-02]
 [-6.49142677e-05]
 [ 9.70642150e-03]
 [ 8.96453804e-03]
 [ 1.36004815e-02]
 [-1.74029978e-03]
 [ 1.54335747e-02]
 [ 9.65855398e-03]
 [ 9.80677540e-03]
 [-3.06444202e-03]
 [ 8.55505109e-04]
 [ 4.64307108e-04]
 [ 1.59565843e-02]
 [ 8.87408285e-03]
 [ 2.88494242e-03]
 [ 1.42097017e-02]
 [ 5.38506830e-03]
 [-2.66395287e-03]
 [ 1.18127355e-02]
 [ 1.58645449e-02]
 [ 1.57446431e-03]
 [-1.44086714e-04]
 [ 8.41144161e-03]
 [-1.54353586e-03]
 [-2.27594264e-03]
 [ 1.55181160e-03]
 [ 1.34121743e-02]
 [ 1.21335155e-02]
 [ 1.02129967e-02]
 [ 1.31526570e-02]
 [ 1.40485412e-02]
 [ 9.02644655e-03]
 [ 8.27708417e-03]
 [ 1.28309529e-02]
 [-3.32221708e-03]
 [ 1.11057910e-03]
 [ 1.24536175e-02]
 [ 4.49220446e-03]
 [ 8.82527054e-03]
 [-3.83326429e-03]
 [ 7.67106372e-03]
 [ 1.34384366e-02]
 [ 8.93065360e-03]
 [ 1.27350331e-02]
 [ 7.43032169e-03]
 [ 1.28322802e-02]
 [ 4.60363582e-03]]
Time taken for LU 0.0007874965667724609
Invers

#Write a program to construct Colley’s matrix and right-hand side


In [ ]:
import numpy as np
from scipy.io import loadmat
data_scores=loadmat("/content/Scores.mat")
Scores=data_scores["Scores"]
games=np.abs(Scores)
total=np.sum(games,axis=1)
ColleyMatrix=2*np.eye(10)+np.diag(total)-games
RightSide=1+0.5*np.sum(Scores,axis=1)
print("ColleyMatrix",ColleyMatrix)
print("Right Side",RightSide)


ColleyMatrix [[11. -1. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. 11. -1. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. 11. -1. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. 11. -1. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. 11. -1. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. 11. -1. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. 11. -1. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. 11. -1. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. 11. -1.]
 [-1. -1. -1. -1. -1. -1. -1. -1. -1. 11.]]
Right Side [-0.5 -1.5 -2.5  2.5  5.5  3.5  0.5 -0.5 -0.5  2.5]


#Write a program to solve Colley’s system of linear equations.

In [ ]:

RanksColley=np.linalg.solve(ColleyMatrix,RightSide)
print("Ranks:",RanksColley)


Ranks: [0.33333333 0.25       0.16666667 0.58333333 0.83333333 0.66666667
 0.41666667 0.33333333 0.33333333 0.58333333]


#Write a program to sort and display team rankings obtained from Colley’s method.

In [ ]:

Teams = [
'Baylor', 'Iowa State', 'University of Kansas', 'Kansas State',
'University of Oklahoma', 'Oklahoma State', 'Texas Christian',
'University of Texas Austin', 'Texas Tech', 'West Virginia'
]
Order=np.argsort(RanksColley)[::-1]
RankDescend=RanksColley[Order]
for i in range(10):
  print(RanksColley[Order[i]],Teams[Order[i]])

   0.833University of Oklahoma   
   0.667Oklahoma State           
   0.583Kansas State             
   0.583West Virginia            
   0.417Texas Christian          
   0.333Baylor                   
   0.333Texas Tech               
   0.333University of Texas Austin
   0.250Iowa State               
   0.167University of Kansas     
